version: '3'

services:
  contacts:
    build: .
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - DBHOST=${DBHOST:-mongodb}
      - DBPORT=${DBPORT:-27017}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - "logsvol:/usr/src/app/logs"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    command: --logpath /var/log/mongodb/db.log
    ports:
      - "${DBPORT:-27017}:27017"
    volumes:
      - "datavol:/data/db"
      - "logsvol:/var/log/mongodb"
volumes:
  logsvol:
    external: true
  datavol:
