version: '3'

services:
  contacts:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
